version = 0.1
[default.deploy.parameters]
stack_name = "hello-world-api"
resolve_s3 = true
s3_prefix = "hello-world-api"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
